In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle

In [2]:
df=pd.read_csv("Diabetes_Testset.csv")
df.head()

Unnamed: 0  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
0         139            5      105             72             29      325   
1         484            0      145              0              0        0   
2          80            3      113             44             13        0   
3         678            3      121             52              0        0   
4         108            3       83             58             31       18   

    BMI  DiabetesPedigreeFunction  Age  Outcome  
0  36.9                     0.159   28        0  
1  44.2                     0.630   31        1  
2  22.4                     0.140   22        0  
3  36.0                     0.127   25        1  
4  34.3                     0.336   25        0

In [3]:
df=df.drop("Unnamed: 0",axis=1)
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            5      105             72             29      325  36.9   
1            0      145              0              0        0  44.2   
2            3      113             44             13        0  22.4   
3            3      121             52              0        0  36.0   
4            3       83             58             31       18  34.3   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.159   28        0  
1                     0.630   31        1  
2                     0.140   22        0  
3                     0.127   25        1  
4                     0.336   25        0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               39 non-null     int64  
 1   Glucose                   39 non-null     int64  
 2   BloodPressure             39 non-null     int64  
 3   SkinThickness             39 non-null     int64  
 4   Insulin                   39 non-null     int64  
 5   BMI                       39 non-null     float64
 6   DiabetesPedigreeFunction  39 non-null     float64
 7   Age                       39 non-null     int64  
 8   Outcome                   39 non-null     int64  
dtypes: float64(2), int64(7)
memory usage: 2.9 KB


In [5]:
df.shape

(39, 9)

In [6]:
x=df['Outcome']

In [7]:
x

0     0
1     1
2     0
3     1
4     0
5     0
6     1
7     0
8     0
9     0
10    1
11    0
12    1
13    0
14    0
15    1
16    1
17    0
18    0
19    0
20    1
21    0
22    1
23    1
24    0
25    0
26    0
27    0
28    1
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    1
37    1
38    1
Name: Outcome, dtype: int64

In [8]:
del df["Outcome"]

In [9]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            5      105             72             29      325  36.9   
1            0      145              0              0        0  44.2   
2            3      113             44             13        0  22.4   
3            3      121             52              0        0  36.0   
4            3       83             58             31       18  34.3   

   DiabetesPedigreeFunction  Age  
0                     0.159   28  
1                     0.630   31  
2                     0.140   22  
3                     0.127   25  
4                     0.336   25

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               39 non-null     int64  
 1   Glucose                   39 non-null     int64  
 2   BloodPressure             39 non-null     int64  
 3   SkinThickness             39 non-null     int64  
 4   Insulin                   39 non-null     int64  
 5   BMI                       39 non-null     float64
 6   DiabetesPedigreeFunction  39 non-null     float64
 7   Age                       39 non-null     int64  
dtypes: float64(2), int64(6)
memory usage: 2.6 KB


In [11]:
df.shape

(39, 8)

In [12]:
lm1 = pickle.load(open('Trained_model_LR.sav', 'rb'))

sc = pickle.load(open('standscaler.sav','rb'))

In [13]:
df = sc.transform(df)

In [28]:
lm1.predict(df)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

In [14]:
pred1 = lm1.predict(df)

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(pred1,x)
print(cm)
accuracy_score(pred1,x)*100

[[24  7]
 [ 1  7]]


79.48717948717949

In [16]:
lm2 = pickle.load(open('Trained_model_Knn.sav', 'rb'))
pred2 = lm2.predict(df)

In [29]:
lm2.predict(df)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1], dtype=int64)

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(pred2,x)
print(cm)
accuracy_score(pred2,x)*100

[[24  8]
 [ 1  6]]


76.92307692307693

In [18]:
lm3 = pickle.load(open('Trained_model_nb.sav', 'rb'))
pred3 = lm3.predict(df)

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(pred3,x)
print(cm)
accuracy_score(pred3,x)*100

[[23  5]
 [ 2  9]]


82.05128205128204

In [20]:
lm4 = pickle.load(open('Trained_model_sv.sav', 'rb'))
pred4 = lm4.predict(df)

In [27]:
lm4.predict(df)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(pred4,x)
print(cm)
accuracy_score(pred4,x)*100

[[25  7]
 [ 0  7]]


82.05128205128204

In [22]:
lm5 = pickle.load(open('Trained_model_dt.sav', 'rb'))
pred5 = lm5.predict(df)

In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(pred5,x)
print(cm)
accuracy_score(pred5,x)*100

[[25  6]
 [ 0  8]]


84.61538461538461

In [24]:
lm6 = pickle.load(open('Trained_model_rf.sav', 'rb'))
pred6 = lm6.predict(df)

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(pred6,x)
print(cm)
accuracy_score(pred6,x)*100

[[25  6]
 [ 0  8]]


84.61538461538461