In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


import numpy as np

from sklearn.datasets import load_digits

dig=load_digits()

In [2]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(dig.data,dig.target,test_size=0.3,random_state=1)

In [3]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [4]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9851851851851852

In [5]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9777777777777777

# ==================== K Fold Cross Validation ================

In [6]:
from sklearn.model_selection import KFold

kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [9]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9851851851851852

In [10]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9851851851851852

# ===============   StratifiedKFold ================

In [13]:
from sklearn.model_selection import StratifiedKFold

folds=StratifiedKFold(n_splits=3)

In [22]:
s1 = []
s2= []
s3= []

for train_index,test_index in kf.split(dig.data):
    x_train,x_test,y_train,y_test = dig.data[train_index],dig.data[test_index],\
    dig.target[train_index],dig.target[test_index]
    s1.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    s2.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    s3.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [19]:
s1

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [20]:
s2

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [23]:
s3

[0.9298831385642737, 0.9432387312186978, 0.9215358931552587]

In [24]:
from sklearn.model_selection import cross_val_score

In [25]:
cross_val_score(LogisticRegression(),dig.data,dig.target)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [26]:
cross_val_score(SVC(),dig.data,dig.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [27]:
cross_val_score(RandomForestClassifier(n_estimators=40),dig.data,dig.target)

array([0.92777778, 0.90277778, 0.95543175, 0.96935933, 0.90807799])

In [28]:
cross_val_score(RandomForestClassifier(n_estimators=5),dig.data,dig.target)

array([0.88333333, 0.81666667, 0.88300836, 0.89972145, 0.8356546 ])